// Generated by CIRCT firtool-1.62.0
module PositQuantizeToInt8(	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7
  input         clock,	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7
                reset,	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7
                io_pir_sign_i_0,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_sign_i_1,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_sign_i_2,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_sign_i_3,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_sign_i_4,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_sign_i_5,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_sign_i_6,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_sign_i_7,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_sign_i_8,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_sign_i_9,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_sign_i_10,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_sign_i_11,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_sign_i_12,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_sign_i_13,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_sign_i_14,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_sign_i_15,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
  input  [7:0]  io_pir_exp_i_0,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_exp_i_1,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_exp_i_2,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_exp_i_3,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_exp_i_4,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_exp_i_5,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_exp_i_6,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_exp_i_7,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_exp_i_8,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_exp_i_9,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_exp_i_10,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_exp_i_11,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_exp_i_12,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_exp_i_13,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_exp_i_14,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_exp_i_15,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
  input  [32:0] io_pir_frac_i_0,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_frac_i_1,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_frac_i_2,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_frac_i_3,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_frac_i_4,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_frac_i_5,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_frac_i_6,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_frac_i_7,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_frac_i_8,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_frac_i_9,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_frac_i_10,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_frac_i_11,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_frac_i_12,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_frac_i_13,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_frac_i_14,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_pir_frac_i_15,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
  output [7:0]  io_int8_o_0,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_int8_o_1,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_int8_o_2,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_int8_o_3,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_int8_o_4,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_int8_o_5,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_int8_o_6,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_int8_o_7,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_int8_o_8,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_int8_o_9,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_int8_o_10,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_int8_o_11,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_int8_o_12,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_int8_o_13,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_int8_o_14,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
                io_int8_o_15,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
  input         io_reset_window,	// src/main/scala/qvu/PositQuantizeToInt8.scala:23:14
  output [32:0] global_max,	// src/main/scala/qvu/PositQuantizeToInt8.scala:37:22
                global_min,	// src/main/scala/qvu/PositQuantizeToInt8.scala:38:22
                global_scale,	// src/main/scala/qvu/PositQuantizeToInt8.scala:39:24
                global_offset	// src/main/scala/qvu/PositQuantizeToInt8.scala:40:25
);

  wire [32:0] _GEN = io_pir_frac_i_0 == 33'h0 ? 33'h0 : 33'h7F;	// src/main/scala/qvu/PositQuantizeToInt8.scala:50:23, :52:19, :53:20, :70:25, :71:32
  wire [32:0] _GEN_0 = io_pir_frac_i_1 == 33'h0 ? 33'h0 : 33'h1FFFFFF80;	// src/main/scala/qvu/PositQuantizeToInt8.scala:50:23, :52:19, :53:20, :70:25, :72:32
  wire [32:0] _GEN_1 = {26'h0, |io_pir_frac_i_2, 6'h0};	// src/main/scala/qvu/PositQuantizeToInt8.scala:50:23, :52:19, :53:20, :70:25
  wire [32:0] _GEN_2 = io_pir_frac_i_3 == 33'h0 ? 33'h0 : 33'h1FFFFFFC0;	// src/main/scala/qvu/PositQuantizeToInt8.scala:50:23, :52:19, :53:20, :70:25, :74:32
  wire [32:0] _GEN_3 = {27'h0, |io_pir_frac_i_4, 5'h0};	// src/main/scala/qvu/PositQuantizeToInt8.scala:50:23, :52:19, :53:20, :70:25
  wire [32:0] _GEN_4 = io_pir_frac_i_5 == 33'h0 ? 33'h0 : 33'h1FFFFFFE0;	// src/main/scala/qvu/PositQuantizeToInt8.scala:50:23, :52:19, :53:20, :70:25, :76:32
  wire [32:0] _GEN_5 = io_pir_frac_i_6 == 33'h0 ? 33'h0 : 33'h64;	// src/main/scala/qvu/PositQuantizeToInt8.scala:50:23, :52:19, :53:20, :70:25, :77:32
  wire [32:0] _GEN_6 = io_pir_frac_i_7 == 33'h0 ? 33'h0 : 33'h1FFFFFF9C;	// src/main/scala/qvu/PositQuantizeToInt8.scala:50:23, :52:19, :53:20, :70:25, :78:32
  wire [32:0] _GEN_7 = io_pir_frac_i_8 == 33'h0 ? 33'h0 : 33'h7F;	// src/main/scala/qvu/PositQuantizeToInt8.scala:50:23, :52:19, :53:20, :70:25, :71:32
  wire [32:0] _GEN_8 = io_pir_frac_i_9 == 33'h0 ? 33'h0 : 33'h1FFFFFF80;	// src/main/scala/qvu/PositQuantizeToInt8.scala:50:23, :52:19, :53:20, :70:25, :72:32
  wire [32:0] _GEN_9 = {26'h0, |io_pir_frac_i_10, 6'h0};	// src/main/scala/qvu/PositQuantizeToInt8.scala:50:23, :52:19, :53:20, :70:25
  wire [32:0] _GEN_10 = io_pir_frac_i_11 == 33'h0 ? 33'h0 : 33'h1FFFFFFC0;	// src/main/scala/qvu/PositQuantizeToInt8.scala:50:23, :52:19, :53:20, :70:25, :74:32
  wire [32:0] _GEN_11 = {27'h0, |io_pir_frac_i_12, 5'h0};	// src/main/scala/qvu/PositQuantizeToInt8.scala:50:23, :52:19, :53:20, :70:25
  wire [32:0] _GEN_12 = io_pir_frac_i_13 == 33'h0 ? 33'h0 : 33'h1FFFFFFE0;	// src/main/scala/qvu/PositQuantizeToInt8.scala:50:23, :52:19, :53:20, :70:25, :76:32
  wire [32:0] _GEN_13 = io_pir_frac_i_14 == 33'h0 ? 33'h0 : 33'h64;	// src/main/scala/qvu/PositQuantizeToInt8.scala:50:23, :52:19, :53:20, :70:25, :77:32
  wire [32:0] _GEN_14 = io_pir_frac_i_15 == 33'h0 ? 33'h0 : 33'h1FFFFFF9C;	// src/main/scala/qvu/PositQuantizeToInt8.scala:50:23, :52:19, :53:20, :70:25, :78:32
  assign io_int8_o_0 =
    $signed(_GEN) > 33'sh7F ? 8'h7F : $signed(_GEN) < -33'sh80 ? 8'h80 : _GEN[7:0];	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7, :52:19, :53:20, :70:25, :71:32, :72:32, :118:{24,33}, :119:20, :120:{30,40}, :121:20, :123:{20,35}
  assign io_int8_o_1 =
    $signed(_GEN_0) > 33'sh7F ? 8'h7F : $signed(_GEN_0) < -33'sh80 ? 8'h80 : _GEN_0[7:0];	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7, :52:19, :53:20, :70:25, :71:32, :72:32, :118:{24,33}, :119:20, :120:{30,40}, :121:20, :123:{20,35}
  assign io_int8_o_2 =
    $signed(_GEN_1) > 33'sh7F
      ? 8'h7F
      : $signed(_GEN_1) < -33'sh80 ? 8'h80 : {1'h0, |io_pir_frac_i_2, 6'h0};	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7, :50:23, :52:19, :53:20, :70:25, :71:32, :72:32, :118:{24,33}, :119:20, :120:{30,40}, :121:20, :123:{20,35}
  assign io_int8_o_3 =
    $signed(_GEN_2) > 33'sh7F ? 8'h7F : $signed(_GEN_2) < -33'sh80 ? 8'h80 : _GEN_2[7:0];	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7, :52:19, :53:20, :70:25, :71:32, :72:32, :118:{24,33}, :119:20, :120:{30,40}, :121:20, :123:{20,35}
  assign io_int8_o_4 =
    $signed(_GEN_3) > 33'sh7F
      ? 8'h7F
      : $signed(_GEN_3) < -33'sh80 ? 8'h80 : {2'h0, |io_pir_frac_i_4, 5'h0};	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7, :50:23, :52:19, :53:20, :70:25, :71:32, :72:32, :118:{24,33}, :119:20, :120:{30,40}, :121:20, :123:{20,35}
  assign io_int8_o_5 =
    $signed(_GEN_4) > 33'sh7F ? 8'h7F : $signed(_GEN_4) < -33'sh80 ? 8'h80 : _GEN_4[7:0];	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7, :52:19, :53:20, :70:25, :71:32, :72:32, :118:{24,33}, :119:20, :120:{30,40}, :121:20, :123:{20,35}
  assign io_int8_o_6 =
    $signed(_GEN_5) > 33'sh7F ? 8'h7F : $signed(_GEN_5) < -33'sh80 ? 8'h80 : _GEN_5[7:0];	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7, :52:19, :53:20, :70:25, :71:32, :72:32, :118:{24,33}, :119:20, :120:{30,40}, :121:20, :123:{20,35}
  assign io_int8_o_7 =
    $signed(_GEN_6) > 33'sh7F ? 8'h7F : $signed(_GEN_6) < -33'sh80 ? 8'h80 : _GEN_6[7:0];	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7, :52:19, :53:20, :70:25, :71:32, :72:32, :118:{24,33}, :119:20, :120:{30,40}, :121:20, :123:{20,35}
  assign io_int8_o_8 =
    $signed(_GEN_7) > 33'sh7F ? 8'h7F : $signed(_GEN_7) < -33'sh80 ? 8'h80 : _GEN_7[7:0];	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7, :52:19, :53:20, :70:25, :71:32, :72:32, :118:{24,33}, :119:20, :120:{30,40}, :121:20, :123:{20,35}
  assign io_int8_o_9 =
    $signed(_GEN_8) > 33'sh7F ? 8'h7F : $signed(_GEN_8) < -33'sh80 ? 8'h80 : _GEN_8[7:0];	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7, :52:19, :53:20, :70:25, :71:32, :72:32, :118:{24,33}, :119:20, :120:{30,40}, :121:20, :123:{20,35}
  assign io_int8_o_10 =
    $signed(_GEN_9) > 33'sh7F
      ? 8'h7F
      : $signed(_GEN_9) < -33'sh80 ? 8'h80 : {1'h0, |io_pir_frac_i_10, 6'h0};	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7, :50:23, :52:19, :53:20, :70:25, :71:32, :72:32, :118:{24,33}, :119:20, :120:{30,40}, :121:20, :123:{20,35}
  assign io_int8_o_11 =
    $signed(_GEN_10) > 33'sh7F
      ? 8'h7F
      : $signed(_GEN_10) < -33'sh80 ? 8'h80 : _GEN_10[7:0];	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7, :52:19, :53:20, :70:25, :71:32, :72:32, :118:{24,33}, :119:20, :120:{30,40}, :121:20, :123:{20,35}
  assign io_int8_o_12 =
    $signed(_GEN_11) > 33'sh7F
      ? 8'h7F
      : $signed(_GEN_11) < -33'sh80 ? 8'h80 : {2'h0, |io_pir_frac_i_12, 5'h0};	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7, :50:23, :52:19, :53:20, :70:25, :71:32, :72:32, :118:{24,33}, :119:20, :120:{30,40}, :121:20, :123:{20,35}
  assign io_int8_o_13 =
    $signed(_GEN_12) > 33'sh7F
      ? 8'h7F
      : $signed(_GEN_12) < -33'sh80 ? 8'h80 : _GEN_12[7:0];	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7, :52:19, :53:20, :70:25, :71:32, :72:32, :118:{24,33}, :119:20, :120:{30,40}, :121:20, :123:{20,35}
  assign io_int8_o_14 =
    $signed(_GEN_13) > 33'sh7F
      ? 8'h7F
      : $signed(_GEN_13) < -33'sh80 ? 8'h80 : _GEN_13[7:0];	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7, :52:19, :53:20, :70:25, :71:32, :72:32, :118:{24,33}, :119:20, :120:{30,40}, :121:20, :123:{20,35}
  assign io_int8_o_15 =
    $signed(_GEN_14) > 33'sh7F
      ? 8'h7F
      : $signed(_GEN_14) < -33'sh80 ? 8'h80 : _GEN_14[7:0];	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7, :52:19, :53:20, :70:25, :71:32, :72:32, :118:{24,33}, :119:20, :120:{30,40}, :121:20, :123:{20,35}
  assign global_max = 33'h7F;	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7, :71:32
  assign global_min = 33'h1FFFFFF80;	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7, :72:32
  assign global_scale = 33'h1;	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7, :86:25
  assign global_offset = 33'h0;	// src/main/scala/qvu/PositQuantizeToInt8.scala:9:7, :53:20
endmodule

