// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VQvuTop.h for the primary calling header

#ifndef VERILATED_VQVUTOP___024ROOT_H_
#define VERILATED_VQVUTOP___024ROOT_H_  // guard

#include "verilated.h"

class VQvuTop__Syms;

class VQvuTop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(io_op,3,0);
        VL_IN8(io_Isposit,0,0);
        VL_IN8(io_Outposit,0,0);
        VL_IN8(io_float_mode,2,0);
        VL_IN8(io_float_posit,0,0);
        VL_IN8(io_src_posit_width,5,0);
        VL_IN8(io_vector_size,2,0);
        VL_IN8(io_dst_posit_width,5,0);
        CData/*2:0*/ QvuTop__DOT__ACTUAL_VECTOR_SIZE;
        CData/*0:0*/ QvuTop__DOT___GEN_5;
        CData/*3:0*/ QvuTop__DOT___GEN_6;
        IData/*31:0*/ QvuTop__DOT____Vcellinp__quantizeInt8__io_pir_exp_i;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_ha15d0789__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_h792c5c44__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_ha10fc7a1__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_hbe60a94c__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_hf2aa9257__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_h4c27362e__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_hf04f431a__0;
        CData/*3:0*/ QvuTop__DOT__decode1__DOT__isNaR;
        CData/*0:0*/ QvuTop__DOT__decode1__DOT____VdfgTmp_h21c2c097__0;
        CData/*0:0*/ QvuTop__DOT__decode1__DOT____VdfgTmp_h217d4d15__0;
        CData/*0:0*/ QvuTop__DOT__decode1__DOT____VdfgTmp_h24cba9c4__0;
        CData/*0:0*/ QvuTop__DOT__decode1__DOT____VdfgTmp_h244a7236__0;
        VlWide<5>/*159:0*/ QvuTop__DOT__decode1__DOT__lzcModule__DOT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ QvuTop__DOT__decode1__DOT__lzcModule_1__DOT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ QvuTop__DOT__decode1__DOT__lzcModule_2__DOT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ QvuTop__DOT__decode1__DOT__lzcModule_3__DOT__gen_lzc__DOT__index_nodes;
        IData/*31:0*/ QvuTop__DOT__decode2__DOT__io_Exp;
        CData/*3:0*/ QvuTop__DOT__decode2__DOT__isNaR;
        CData/*0:0*/ QvuTop__DOT__decode2__DOT____VdfgTmp_h21c2c097__0;
        CData/*0:0*/ QvuTop__DOT__decode2__DOT____VdfgTmp_h217d4d15__0;
        CData/*0:0*/ QvuTop__DOT__decode2__DOT____VdfgTmp_h24cba9c4__0;
        CData/*0:0*/ QvuTop__DOT__decode2__DOT____VdfgTmp_h244a7236__0;
        VlWide<5>/*159:0*/ QvuTop__DOT__decode2__DOT__lzcModule__DOT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ QvuTop__DOT__decode2__DOT__lzcModule_1__DOT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ QvuTop__DOT__decode2__DOT__lzcModule_2__DOT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ QvuTop__DOT__decode2__DOT__lzcModule_3__DOT__gen_lzc__DOT__index_nodes;
        CData/*3:0*/ QvuTop__DOT__floatDecode1__DOT___GEN;
        CData/*3:0*/ QvuTop__DOT__floatDecode1__DOT___GEN_0;
        CData/*7:0*/ QvuTop__DOT__floatDecode1__DOT____VdfgTmp_h8929cb16__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode1__DOT____VdfgTmp_h89ab41bc__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode1__DOT____VdfgTmp_h8a58f023__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode1__DOT____VdfgTmp_h8aa26e89__0;
        CData/*3:0*/ QvuTop__DOT__floatDecode2__DOT___GEN;
        CData/*3:0*/ QvuTop__DOT__floatDecode2__DOT___GEN_0;
        CData/*7:0*/ QvuTop__DOT__floatDecode2__DOT____VdfgTmp_h8929cb16__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode2__DOT____VdfgTmp_h89ab41bc__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode2__DOT____VdfgTmp_h8a58f023__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode2__DOT____VdfgTmp_h8aa26e89__0;
        CData/*0:0*/ QvuTop__DOT__quantizeInt8__DOT__batchHasData;
        CData/*1:0*/ QvuTop__DOT__quantizeInt8__DOT__state;
        CData/*5:0*/ QvuTop__DOT__quantizeInt8__DOT__shiftVal;
        CData/*0:0*/ QvuTop__DOT__quantizeInt8__DOT___GEN_0;
        CData/*5:0*/ QvuTop__DOT__quantizeInt8__DOT__shiftVal_1;
        CData/*0:0*/ QvuTop__DOT__quantizeInt8__DOT___GEN_3;
        CData/*5:0*/ QvuTop__DOT__quantizeInt8__DOT__shiftVal_2;
        CData/*0:0*/ QvuTop__DOT__quantizeInt8__DOT___GEN_6;
        CData/*5:0*/ QvuTop__DOT__quantizeInt8__DOT__shiftVal_3;
        CData/*0:0*/ QvuTop__DOT__quantizeInt8__DOT___GEN_9;
        CData/*0:0*/ QvuTop__DOT__quantizeInt8__DOT__needRounding;
        CData/*0:0*/ QvuTop__DOT__quantizeInt8__DOT__needRounding_1;
    };
    struct {
        CData/*0:0*/ QvuTop__DOT__quantizeInt8__DOT__needRounding_2;
        CData/*0:0*/ QvuTop__DOT__quantizeInt8__DOT__needRounding_3;
        CData/*0:0*/ QvuTop__DOT__quantizeInt8__DOT__unnamedblk1__DOT___GEN_14;
        CData/*0:0*/ QvuTop__DOT__quantizeInt8__DOT__unnamedblk1__DOT___GEN_15;
        CData/*0:0*/ QvuTop__DOT__quantizeInt8__DOT__unnamedblk1__DOT___GEN_16;
        CData/*0:0*/ QvuTop__DOT__quantizeInt8__DOT__unnamedblk1__DOT___GEN_17;
        CData/*0:0*/ QvuTop__DOT__quantizeInt8__DOT__unnamedblk1__DOT___GEN_18;
        CData/*0:0*/ QvuTop__DOT__quantizeInt8__DOT__unnamedblk1__DOT___GEN_19;
        CData/*0:0*/ QvuTop__DOT__quantizeInt8__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_20;
        CData/*0:0*/ QvuTop__DOT__quantizeInt8__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_21;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__batchHasData;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__state;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__needRounding;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__roundingDirection;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__needRounding_1;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__roundingDirection_1;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__needRounding_2;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__roundingDirection_2;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__needRounding_3;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__roundingDirection_3;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_17;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_18;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_19;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_20;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_21;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_31;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_32;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_33;
        CData/*2:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__safeIndex;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_34;
        CData/*2:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__safeIndex_1;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_35;
        CData/*2:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__safeIndex_2;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_36;
        CData/*2:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__safeIndex_3;
        CData/*7:0*/ QvuTop__DOT__quantizeFP4__DOT__windowValid;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__windowPtr;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__batchHasData;
        CData/*1:0*/ QvuTop__DOT__quantizeFP4__DOT__state;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__quantIndex;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__quantIndex_1;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__quantIndex_2;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__quantIndex_3;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_3;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_4;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_5;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_6;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_7;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_8;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_9;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_10;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_11;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_12;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_13;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_14;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_15;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_16;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_17;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_18;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_19;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_20;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_21;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_22;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_23;
    };
    struct {
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_24;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_25;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_26;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMax_leftMax_leftMax_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_27;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_28;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMax_leftMax_rightMax_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMax_leftMax_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_29;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_30;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMax_rightMax_leftMax_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_31;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_32;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMax_rightMax_rightMax_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMax_rightMax_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMax_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_33;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_34;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMin_leftMin_leftMin_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_35;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_36;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMin_leftMin_rightMin_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMin_leftMin_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_37;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_38;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMin_rightMin_leftMin_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_39;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_40;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMin_rightMin_rightMin_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMin_rightMin_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMin_T;
        CData/*3:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___windowPtr_T_2;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hdd03ac44__0;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hdd893d74__0;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hdee4f6f7__0;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hdbc354e5__0;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode1__DOT__lzcModule__DOT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode1__DOT__lzcModule_1__DOT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode1__DOT__lzcModule_2__DOT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode1__DOT__lzcModule_3__DOT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode2__DOT__lzcModule__DOT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode2__DOT__lzcModule_1__DOT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode2__DOT__lzcModule_2__DOT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode2__DOT__lzcModule_3__DOT__gen_lzc__DOT__index_nodes;
        CData/*0:0*/ __VstlDidInit;
        CData/*0:0*/ __VicoDidInit;
        CData/*0:0*/ __Vtrigrprev__TOP__clock;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        VlWide<4>/*127:0*/ QvuTop__DOT__quantizeInt4__DOT__histogram;
        SData/*15:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___histogram_T_2;
        SData/*15:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___histogram_T_6;
        SData/*15:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___histogram_T_10;
        SData/*15:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___histogram_T_14;
        SData/*15:0*/ __VdfgTmp_h92081510__0;
        SData/*14:0*/ __VdfgTmp_h9981df73__0;
        SData/*14:0*/ __VdfgTmp_h6db38b42__0;
        VL_IN(io_posit_i1_0,31,0);
        VL_IN(io_posit_i1_1,31,0);
        VL_IN(io_posit_i1_2,31,0);
        VL_IN(io_posit_i1_3,31,0);
        VL_IN(io_posit_i2_0,31,0);
        VL_IN(io_posit_i2_1,31,0);
        VL_IN(io_posit_i2_2,31,0);
    };
    struct {
        VL_IN(io_posit_i2_3,31,0);
        VL_OUT(io_posit_o_0,31,0);
        VL_OUT(io_posit_o_1,31,0);
        VL_OUT(io_posit_o_2,31,0);
        VL_OUT(io_posit_o_3,31,0);
        VL_OUT(io_posit_dot_o,31,0);
        VL_OUT(io_int_o_0,31,0);
        VL_OUT(io_int_o_1,31,0);
        VL_OUT(io_int_o_2,31,0);
        VL_OUT(io_int_o_3,31,0);
        IData/*30:0*/ QvuTop__DOT__decode1__DOT___barrel_shifter_3_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode1__DOT___barrel_shifter_2_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode1__DOT___barrel_shifter_1_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode1__DOT___barrel_shifter_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode1__DOT___operand_0_T_6;
        IData/*30:0*/ QvuTop__DOT__decode1__DOT___operand_1_T_6;
        IData/*30:0*/ QvuTop__DOT__decode1__DOT___operand_2_T_6;
        IData/*30:0*/ QvuTop__DOT__decode1__DOT___operand_3_T_6;
        IData/*30:0*/ QvuTop__DOT__decode1__DOT____Vcellinp__lzcModule__in_i;
        IData/*30:0*/ QvuTop__DOT__decode1__DOT____Vcellinp__lzcModule_1__in_i;
        IData/*30:0*/ QvuTop__DOT__decode1__DOT____Vcellinp__lzcModule_2__in_i;
        IData/*30:0*/ QvuTop__DOT__decode1__DOT____Vcellinp__lzcModule_3__in_i;
        IData/*31:0*/ QvuTop__DOT__decode1__DOT__lzcModule__DOT__gen_lzc__DOT__sel_nodes;
        IData/*30:0*/ QvuTop__DOT__decode1__DOT__lzcModule__DOT__gen_lzc__DOT__in_tmp;
        IData/*31:0*/ QvuTop__DOT__decode1__DOT__lzcModule_1__DOT__gen_lzc__DOT__sel_nodes;
        IData/*30:0*/ QvuTop__DOT__decode1__DOT__lzcModule_1__DOT__gen_lzc__DOT__in_tmp;
        IData/*31:0*/ QvuTop__DOT__decode1__DOT__lzcModule_2__DOT__gen_lzc__DOT__sel_nodes;
        IData/*30:0*/ QvuTop__DOT__decode1__DOT__lzcModule_2__DOT__gen_lzc__DOT__in_tmp;
        IData/*31:0*/ QvuTop__DOT__decode1__DOT__lzcModule_3__DOT__gen_lzc__DOT__sel_nodes;
        IData/*30:0*/ QvuTop__DOT__decode1__DOT__lzcModule_3__DOT__gen_lzc__DOT__in_tmp;
        IData/*30:0*/ QvuTop__DOT__decode2__DOT___barrel_shifter_3_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode2__DOT___barrel_shifter_2_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode2__DOT___barrel_shifter_1_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode2__DOT___barrel_shifter_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode2__DOT___operand_0_T_6;
        IData/*30:0*/ QvuTop__DOT__decode2__DOT___operand_1_T_6;
        IData/*30:0*/ QvuTop__DOT__decode2__DOT___operand_2_T_6;
        IData/*30:0*/ QvuTop__DOT__decode2__DOT___operand_3_T_6;
        IData/*30:0*/ QvuTop__DOT__decode2__DOT____Vcellinp__lzcModule__in_i;
        IData/*30:0*/ QvuTop__DOT__decode2__DOT____Vcellinp__lzcModule_1__in_i;
        IData/*30:0*/ QvuTop__DOT__decode2__DOT____Vcellinp__lzcModule_2__in_i;
        IData/*30:0*/ QvuTop__DOT__decode2__DOT____Vcellinp__lzcModule_3__in_i;
        IData/*31:0*/ QvuTop__DOT__decode2__DOT__lzcModule__DOT__gen_lzc__DOT__sel_nodes;
        IData/*30:0*/ QvuTop__DOT__decode2__DOT__lzcModule__DOT__gen_lzc__DOT__in_tmp;
        IData/*31:0*/ QvuTop__DOT__decode2__DOT__lzcModule_1__DOT__gen_lzc__DOT__sel_nodes;
        IData/*30:0*/ QvuTop__DOT__decode2__DOT__lzcModule_1__DOT__gen_lzc__DOT__in_tmp;
        IData/*31:0*/ QvuTop__DOT__decode2__DOT__lzcModule_2__DOT__gen_lzc__DOT__sel_nodes;
        IData/*30:0*/ QvuTop__DOT__decode2__DOT__lzcModule_2__DOT__gen_lzc__DOT__in_tmp;
        IData/*31:0*/ QvuTop__DOT__decode2__DOT__lzcModule_3__DOT__gen_lzc__DOT__sel_nodes;
        IData/*30:0*/ QvuTop__DOT__decode2__DOT__lzcModule_3__DOT__gen_lzc__DOT__in_tmp;
        IData/*22:0*/ QvuTop__DOT__floatDecode1__DOT____VdfgTmp_h8a383c23__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode1__DOT____VdfgTmp_h898ddcf9__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode1__DOT____VdfgTmp_h8933512e__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode1__DOT____VdfgTmp_h88bc2594__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode2__DOT____VdfgTmp_h8a383c23__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode2__DOT____VdfgTmp_h898ddcf9__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode2__DOT____VdfgTmp_h8933512e__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode2__DOT____VdfgTmp_h88bc2594__0;
        IData/*31:0*/ QvuTop__DOT__quantizeInt8__DOT__shiftedFrac;
        IData/*31:0*/ QvuTop__DOT__quantizeInt8__DOT__shiftedFrac_1;
        IData/*31:0*/ QvuTop__DOT__quantizeInt8__DOT__shiftedFrac_2;
        IData/*31:0*/ QvuTop__DOT__quantizeInt8__DOT__shiftedFrac_3;
        IData/*27:0*/ QvuTop__DOT__quantizeInt8__DOT____VdfgTmp_hdf96a6fc__0;
        IData/*27:0*/ QvuTop__DOT__quantizeInt8__DOT____VdfgTmp_hdcaf2b43__0;
    };
    struct {
        IData/*27:0*/ QvuTop__DOT__quantizeInt8__DOT____VdfgTmp_hd95c8805__0;
        IData/*27:0*/ QvuTop__DOT__quantizeInt8__DOT____VdfgTmp_hd9d61bde__0;
        IData/*19:0*/ QvuTop__DOT__quantizeInt4__DOT__histogramTotal;
        IData/*19:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___cdf_1_T;
        IData/*19:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___cdf_2_T;
        IData/*19:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___cdf_3_T;
        IData/*19:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___cdf_4_T;
        IData/*19:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___cdf_5_T;
        IData/*19:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___cdf_6_T;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_22;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__lowerThreshold;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___upperThreshold_T;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_23;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_24;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_25;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_26;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_27;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_28;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_29;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_30;
        IData/*24:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hdc3001b5__0;
        IData/*24:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hdc8dcd07__0;
        IData/*24:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hd93d690c__0;
        IData/*24:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hd9b73fc0__0;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode1__DOT__lzcModule__DOT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode1__DOT__lzcModule_1__DOT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode1__DOT__lzcModule_2__DOT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode1__DOT__lzcModule_3__DOT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode2__DOT__lzcModule__DOT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode2__DOT__lzcModule_1__DOT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode2__DOT__lzcModule_2__DOT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode2__DOT__lzcModule_3__DOT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __VstlIterCount;
        IData/*31:0*/ __VicoIterCount;
        IData/*31:0*/ __VactIterCount;
        VL_IN64(io_float_i_0,63,0);
        VL_IN64(io_float_i_1,63,0);
        VL_IN64(io_float_i_2,63,0);
        VL_IN64(io_float_i_3,63,0);
        VL_IN64(io_float_i2_0,63,0);
        VL_IN64(io_float_i2_1,63,0);
        VL_IN64(io_float_i2_2,63,0);
        VL_IN64(io_float_i2_3,63,0);
        VL_OUT64(io_float_o_0,63,0);
        VL_OUT64(io_float_o_1,63,0);
        VL_OUT64(io_float_o_2,63,0);
        VL_OUT64(io_float_o_3,63,0);
        VL_OUT64(io_float_dot_o,63,0);
        VlWide<5>/*131:0*/ QvuTop__DOT____Vcellinp__quantizeInt8__io_pir_frac_i;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT__globalMax;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT__globalMin;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT__globalScale;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT__globalOffset;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT__batchMax;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT__batchMin;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT___GEN_1;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT___GEN_4;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT___GEN_7;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT___GEN_10;
        QData/*33:0*/ QvuTop__DOT__quantizeInt8__DOT___GEN_11;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT__remainder;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT___GEN_12;
        QData/*33:0*/ QvuTop__DOT__quantizeInt8__DOT___roundedValue_T_4;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT__remainder_1;
    };
    struct {
        QData/*33:0*/ QvuTop__DOT__quantizeInt8__DOT___roundedValue_T_10;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT__remainder_2;
        QData/*33:0*/ QvuTop__DOT__quantizeInt8__DOT___roundedValue_T_16;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT__remainder_3;
        QData/*33:0*/ QvuTop__DOT__quantizeInt8__DOT___roundedValue_T_22;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT__unnamedblk1__DOT__unnamedblk2__DOT___range_T;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT__unnamedblk1__DOT__unnamedblk2__DOT___range_T_7;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT__unnamedblk1__DOT__unnamedblk2__DOT___mid_T;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT__unnamedblk1__DOT__unnamedblk2__DOT___mid_T_3;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT____VdfgTmp_hdf96a634__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT____VdfgTmp_hdcaf4442__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT____VdfgTmp_hd95c8ec3__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt8__DOT____VdfgTmp_hd9d61d93__0;
        QData/*33:0*/ QvuTop__DOT__quantizeInt8__DOT____VdfgTmp_h8d89f6e8__0;
        QData/*33:0*/ QvuTop__DOT__quantizeInt8__DOT____VdfgTmp_h421836e6__0;
        QData/*33:0*/ QvuTop__DOT__quantizeInt8__DOT____VdfgTmp_h44fc25d8__0;
        QData/*33:0*/ QvuTop__DOT__quantizeInt8__DOT____VdfgTmp_h964749d0__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__globalMax;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__globalMin;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__globalScale;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__globalOffset;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__batchMax;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__batchMin;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_12;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__scaledValue;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__remainder;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__tempIdx;
        QData/*36:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_14;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_15;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__quantizedValue;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__scaledValue_1;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__remainder_1;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__tempIdx_1;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__quantizedValue_1;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__scaledValue_2;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__remainder_2;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__tempIdx_2;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__quantizedValue_2;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__scaledValue_3;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__remainder_3;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__tempIdx_3;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__quantizedValue_3;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___dataRange_T;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__binWidth_4;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__effectiveMin;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__effectiveMax;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk2__DOT___dataRange_T_8;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk2__DOT___dataRange_T_15;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk2__DOT___mid_T;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___binWidth_T;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__binWidth;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___tempIndex_T;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__tempIndex;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___binWidth_T_11;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__binWidth_1;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___tempIndex_T_9;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__tempIndex_1;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___binWidth_T_22;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__binWidth_2;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___tempIndex_T_18;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__tempIndex_2;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___binWidth_T_33;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__binWidth_3;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___tempIndex_T_27;
    };
    struct {
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__tempIndex_3;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_he7b16fba__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_h601d99d2__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hff625ee6__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_h9762a8ae__0;
        QData/*36:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_h5d60b427__0;
        VlWide<9>/*263:0*/ QvuTop__DOT__quantizeFP4__DOT__windowMax;
        VlWide<9>/*263:0*/ QvuTop__DOT__quantizeFP4__DOT__windowMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__globalMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__globalMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__globalScale;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__batchMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__batchMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT___GEN;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT___GEN_0;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT___GEN_1;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT___GEN_2;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__valueAbs;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__valueAbs_1;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__valueAbs_2;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__valueAbs_3;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_leftMax_leftMax_leftMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_leftMax_leftMax_rightMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_leftMax_leftMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_leftMax_rightMax_leftMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_leftMax_rightMax_rightMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_leftMax_rightMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_leftMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_rightMax_leftMax_leftMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_rightMax_leftMax_rightMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_rightMax_leftMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_rightMax_rightMax_leftMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_rightMax_rightMax_rightMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_rightMax_rightMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_rightMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_leftMin_leftMin_leftMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_leftMin_leftMin_rightMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_leftMin_leftMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_leftMin_rightMin_leftMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_leftMin_rightMin_rightMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_leftMin_rightMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_leftMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_rightMin_leftMin_leftMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_rightMin_leftMin_rightMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_rightMin_leftMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_rightMin_rightMin_leftMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_rightMin_rightMin_rightMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_rightMin_rightMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_rightMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__dataRange;
        QData/*32:0*/ __VdfgTmp_h9c9ab370__0;
        QData/*32:0*/ __VdfgTmp_h46be9c78__0;
        QData/*32:0*/ __VdfgTmp_h43a98faf__0;
        QData/*32:0*/ __VdfgTmp_haed5c1a2__0;
        VlUnpacked<CData/*0:0*/, 23> __Vm_traceActivity;
    };
    VlTriggerVec<17> __VstlTriggered;
    VlTriggerVec<17> __VicoTriggered;
    VlTriggerVec<17> __VactTriggered;
    VlTriggerVec<17> __VnbaTriggered;

    // INTERNAL VARIABLES
    VQvuTop__Syms* const vlSymsp;

    // CONSTRUCTORS
    VQvuTop___024root(VQvuTop__Syms* symsp, const char* v__name);
    ~VQvuTop___024root();
    VL_UNCOPYABLE(VQvuTop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
