// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VQvuTop.h for the primary calling header

#ifndef VERILATED_VQVUTOP___024ROOT_H_
#define VERILATED_VQVUTOP___024ROOT_H_  // guard

#include "verilated.h"

class VQvuTop__Syms;
class VQvuTop_LZC__M1_W1f;


class VQvuTop___024root final : public VerilatedModule {
  public:
    // CELLS
    VQvuTop_LZC__M1_W1f* __PVT__QvuTop__DOT__decode__DOT__lzcModule;
    VQvuTop_LZC__M1_W1f* __PVT__QvuTop__DOT__decode__DOT__lzcModule_1;
    VQvuTop_LZC__M1_W1f* __PVT__QvuTop__DOT__decode__DOT__lzcModule_2;
    VQvuTop_LZC__M1_W1f* __PVT__QvuTop__DOT__decode__DOT__lzcModule_3;
    VQvuTop_LZC__M1_W1f* __PVT__QvuTop__DOT__decode__DOT__lzcModule_4;
    VQvuTop_LZC__M1_W1f* __PVT__QvuTop__DOT__decode__DOT__lzcModule_5;
    VQvuTop_LZC__M1_W1f* __PVT__QvuTop__DOT__decode__DOT__lzcModule_6;
    VQvuTop_LZC__M1_W1f* __PVT__QvuTop__DOT__decode__DOT__lzcModule_7;
    VQvuTop_LZC__M1_W1f* __PVT__QvuTop__DOT__decode__DOT__lzcModule_8;
    VQvuTop_LZC__M1_W1f* __PVT__QvuTop__DOT__decode__DOT__lzcModule_9;
    VQvuTop_LZC__M1_W1f* __PVT__QvuTop__DOT__decode__DOT__lzcModule_10;
    VQvuTop_LZC__M1_W1f* __PVT__QvuTop__DOT__decode__DOT__lzcModule_11;
    VQvuTop_LZC__M1_W1f* __PVT__QvuTop__DOT__decode__DOT__lzcModule_12;
    VQvuTop_LZC__M1_W1f* __PVT__QvuTop__DOT__decode__DOT__lzcModule_13;
    VQvuTop_LZC__M1_W1f* __PVT__QvuTop__DOT__decode__DOT__lzcModule_14;
    VQvuTop_LZC__M1_W1f* __PVT__QvuTop__DOT__decode__DOT__lzcModule_15;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(io_op,3,0);
        VL_IN8(io_Isposit,0,0);
        VL_IN8(io_Outposit,0,0);
        VL_IN8(io_float_mode,2,0);
        VL_IN8(io_float_posit,0,0);
        VL_IN8(io_src_posit_width,5,0);
        VL_IN8(io_vector_size,2,0);
        VL_IN8(io_dst_posit_width,5,0);
        VL_IN8(io_reset_window,0,0);
        CData/*4:0*/ QvuTop__DOT__ACTUAL_VECTOR_SIZE;
        CData/*3:0*/ QvuTop__DOT___GEN_0;
        CData/*4:0*/ QvuTop__DOT__resetCounter;
        CData/*0:0*/ QvuTop__DOT___GEN_6;
        VlWide<4>/*127:0*/ QvuTop__DOT____Vcellinp__quantizeInt8__io_pir_exp_i;
        VlWide<4>/*127:0*/ QvuTop__DOT____Vcellout__quantizeFP8__io_fp8_o;
        QData/*63:0*/ QvuTop__DOT____Vcellout__quantizeFP4__io_fp4_o;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_h9b1a73b4__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_h07168e9e__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_h60d0e577__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_hd2b53c8a__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_h3458467d__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_hd84f4eef__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_hdbc09056__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_h657998f6__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_h672aad8b__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_h433f84f8__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_h63b3fc32__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_h5fdab54b__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_h738293b2__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_h5a247d4f__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_hef4171a5__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_h0037cc42__0;
        CData/*0:0*/ QvuTop__DOT____VdfgTmp_h62563a14__0;
        CData/*0:0*/ QvuTop__DOT__decode__DOT____VdfgTmp_hcfb253e9__0;
        CData/*0:0*/ QvuTop__DOT__decode__DOT____VdfgTmp_hcf4be793__0;
        CData/*0:0*/ QvuTop__DOT__decode__DOT____VdfgTmp_hcecc844e__0;
        CData/*0:0*/ QvuTop__DOT__decode__DOT____VdfgTmp_h2a2a10e4__0;
        CData/*0:0*/ QvuTop__DOT__decode__DOT____VdfgTmp_h25bc0d63__0;
        CData/*0:0*/ QvuTop__DOT__decode__DOT____VdfgTmp_h25331089__0;
        CData/*0:0*/ QvuTop__DOT__decode__DOT____VdfgTmp_h24af6ee8__0;
        CData/*0:0*/ QvuTop__DOT__decode__DOT____VdfgTmp_h281ce652__0;
        CData/*0:0*/ QvuTop__DOT__decode__DOT____VdfgTmp_h2babc25d__0;
        CData/*0:0*/ QvuTop__DOT__decode__DOT____VdfgTmp_h2b2d736f__0;
        CData/*0:0*/ QvuTop__DOT__decode__DOT____VdfgTmp_h2aaec35a__0;
        CData/*0:0*/ QvuTop__DOT__decode__DOT____VdfgTmp_h263440d8__0;
        CData/*0:0*/ QvuTop__DOT__decode__DOT____VdfgTmp_h21c2c097__0;
        CData/*0:0*/ QvuTop__DOT__decode__DOT____VdfgTmp_h217d4d15__0;
        CData/*0:0*/ QvuTop__DOT__decode__DOT____VdfgTmp_h24cba9c4__0;
        CData/*0:0*/ QvuTop__DOT__decode__DOT____VdfgTmp_h244a7236__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8929cb16__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h89ab41bc__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8a58f023__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8aa26e89__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8b0ae1f8__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8b957352__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8c0d968d__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8c8c6027__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8d1d245a__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_hf27fc7c0__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8e2c350f__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8e96a8b5__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8f0f6e8c__0;
    };
    struct {
        CData/*7:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8f89e526__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h905e77b9__0;
        CData/*7:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h90d0fe13__0;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__batchHasData;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__state;
        CData/*5:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftVal;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_0;
        CData/*5:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftVal_1;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_3;
        CData/*5:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftVal_2;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_6;
        CData/*5:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftVal_3;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_9;
        CData/*5:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftVal_4;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_12;
        CData/*5:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftVal_5;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_15;
        CData/*5:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftVal_6;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_18;
        CData/*5:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftVal_7;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_21;
        CData/*5:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftVal_8;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_24;
        CData/*5:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftVal_9;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_27;
        CData/*5:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftVal_10;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_30;
        CData/*5:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftVal_11;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_33;
        CData/*5:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftVal_12;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_36;
        CData/*5:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftVal_13;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_39;
        CData/*5:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftVal_14;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_42;
        CData/*5:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftVal_15;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_45;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__needRounding;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__roundingDirection;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__needRounding_1;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__roundingDirection_1;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__needRounding_2;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__roundingDirection_2;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__needRounding_3;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__roundingDirection_3;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__needRounding_4;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__roundingDirection_4;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__needRounding_5;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__roundingDirection_5;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__needRounding_6;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__roundingDirection_6;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__needRounding_7;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__roundingDirection_7;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__needRounding_8;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__roundingDirection_8;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__needRounding_9;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__roundingDirection_9;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__needRounding_10;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__roundingDirection_10;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__needRounding_11;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__roundingDirection_11;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__needRounding_12;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__roundingDirection_12;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__needRounding_13;
    };
    struct {
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__roundingDirection_13;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__needRounding_14;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__roundingDirection_14;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__needRounding_15;
        CData/*1:0*/ QvuTop__DOT__quantizeInt4__DOT__roundingDirection_15;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_53;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_54;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_55;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_56;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_57;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_58;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_59;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_60;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_61;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_62;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_63;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_64;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_65;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_66;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_67;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_68;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_69;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_79;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_80;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_81;
        CData/*2:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__safeIndex;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_82;
        CData/*2:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__safeIndex_1;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_83;
        CData/*2:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__safeIndex_2;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_84;
        CData/*2:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__safeIndex_3;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_85;
        CData/*2:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__safeIndex_4;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_86;
        CData/*2:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__safeIndex_5;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_87;
        CData/*2:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__safeIndex_6;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_88;
        CData/*2:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__safeIndex_7;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_89;
        CData/*2:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__safeIndex_8;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_90;
        CData/*2:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__safeIndex_9;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_91;
        CData/*2:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__safeIndex_10;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_92;
        CData/*2:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__safeIndex_11;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_93;
        CData/*2:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__safeIndex_12;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_94;
        CData/*2:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__safeIndex_13;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_95;
        CData/*2:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__safeIndex_14;
        CData/*0:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___GEN_96;
        CData/*2:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__safeIndex_15;
        CData/*7:0*/ QvuTop__DOT__quantizeFP4__DOT__windowValid;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__windowPtr;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__batchHasData;
        CData/*1:0*/ QvuTop__DOT__quantizeFP4__DOT__state;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__quantIndex;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__quantIndex_1;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__quantIndex_2;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__quantIndex_3;
    };
    struct {
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__quantIndex_4;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__quantIndex_5;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__quantIndex_6;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__quantIndex_7;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__quantIndex_8;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__quantIndex_9;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__quantIndex_10;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__quantIndex_11;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__quantIndex_12;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__quantIndex_13;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__quantIndex_14;
        CData/*2:0*/ QvuTop__DOT__quantizeFP4__DOT__quantIndex_15;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_15;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_16;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_17;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_18;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_19;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_20;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_21;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_22;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_23;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_24;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_25;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_26;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_27;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_28;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_29;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_30;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_31;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_32;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_33;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_34;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_35;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_36;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_37;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_38;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_39;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_40;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_41;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_42;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_43;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_44;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_45;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_46;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_47;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT___GEN_48;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_49;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_50;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMax_leftMax_leftMax_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_51;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_52;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMax_leftMax_rightMax_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMax_leftMax_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_53;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_54;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMax_rightMax_leftMax_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_55;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_56;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMax_rightMax_rightMax_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMax_rightMax_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMax_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_57;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_58;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMin_leftMin_leftMin_T;
    };
    struct {
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_59;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_60;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMin_leftMin_rightMin_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMin_leftMin_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_61;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_62;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMin_rightMin_leftMin_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_63;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_64;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMin_rightMin_rightMin_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMin_rightMin_T;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___effectiveMin_T;
        CData/*3:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT___windowPtr_T_2;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hd3016326__0;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hd3bf0dae__0;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_h34eabf7b__0;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_h349b44b9__0;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hd91def4b__0;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hde76be47__0;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_h3af5d97e__0;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_h3b636de0__0;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_h37f6fbe9__0;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_h37932ea5__0;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hd80e3daa__0;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hd88100fc__0;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hdd03ac44__0;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hdd893d74__0;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hdee4f6f7__0;
        CData/*0:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hdbc354e5__0;
        CData/*7:0*/ __VdfgTmp_hece37c2e__0;
        CData/*6:0*/ __VdfgTmp_h45a06809__0;
        CData/*6:0*/ __VdfgTmp_h54d188b7__0;
        CData/*6:0*/ __VdfgTmp_h8a2eaf1f__0;
        CData/*6:0*/ __VdfgTmp_h95bf39bd__0;
        CData/*6:0*/ __VdfgTmp_he5b81198__0;
        CData/*6:0*/ __VdfgTmp_h66c1db1c__0;
        CData/*6:0*/ __VdfgTmp_h47b9a3d0__0;
        CData/*0:0*/ __VdfgTmp_hbb02c542__0;
        CData/*6:0*/ __VdfgTmp_hab31a8ed__0;
        CData/*6:0*/ __VdfgTmp_h90cf73ba__0;
        CData/*6:0*/ __VdfgTmp_ha24b52a4__0;
        CData/*6:0*/ __VdfgTmp_h31cfcd1e__0;
        CData/*6:0*/ __VdfgTmp_hd07f1d61__0;
        CData/*6:0*/ __VdfgTmp_h4ecb4224__0;
        CData/*6:0*/ __VdfgTmp_h34744805__0;
        CData/*6:0*/ __VdfgTmp_h03f676fd__0;
        CData/*0:0*/ __VdfgTmp_he1263253__0;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_15____PVT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_14____PVT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_13____PVT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_12____PVT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_11____PVT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_10____PVT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_9____PVT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_8____PVT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_7____PVT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_6____PVT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_5____PVT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_4____PVT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_3____PVT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_2____PVT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_1____PVT__gen_lzc__DOT__index_nodes;
        VlWide<5>/*159:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule____PVT__gen_lzc__DOT__index_nodes;
        CData/*0:0*/ __VstlDidInit;
    };
    struct {
        CData/*0:0*/ __VicoDidInit;
        CData/*0:0*/ __Vtrigrprev__TOP__clock;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ QvuTop__DOT___GEN_7;
        VlWide<5>/*143:0*/ QvuTop__DOT____Vcellout__floatDecode__io_Exp;
        VlWide<8>/*255:0*/ QvuTop__DOT____Vcellout__quantizeFP16__io_fp16_o;
        SData/*15:0*/ QvuTop__DOT__decode__DOT__isNaR;
        SData/*15:0*/ QvuTop__DOT__floatDecode__DOT__io_isNaN;
        SData/*15:0*/ QvuTop__DOT__floatDecode__DOT___GEN;
        SData/*15:0*/ QvuTop__DOT__floatDecode__DOT___GEN_0;
        VlWide<4>/*127:0*/ QvuTop__DOT__quantizeInt4__DOT__histogram;
        SData/*15:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___histogram_T_2;
        SData/*15:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___histogram_T_6;
        SData/*15:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___histogram_T_10;
        SData/*15:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___histogram_T_14;
        SData/*15:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___histogram_T_18;
        SData/*15:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___histogram_T_22;
        SData/*15:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___histogram_T_26;
        SData/*15:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___histogram_T_30;
        SData/*15:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___histogram_T_34;
        SData/*15:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___histogram_T_38;
        SData/*15:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___histogram_T_42;
        SData/*15:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___histogram_T_46;
        SData/*15:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___histogram_T_50;
        SData/*15:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___histogram_T_54;
        SData/*15:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___histogram_T_58;
        SData/*15:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___histogram_T_62;
        SData/*15:0*/ __VdfgTmp_hc6e18ff1__0;
        SData/*14:0*/ __VdfgTmp_hd12e3618__0;
        SData/*14:0*/ __VdfgTmp_h15c5203c__0;
        SData/*14:0*/ __VdfgTmp_h1e6be8f2__0;
        SData/*14:0*/ __VdfgTmp_h29201396__0;
        SData/*14:0*/ __VdfgTmp_h1fa020bc__0;
        SData/*14:0*/ __VdfgTmp_h3f6e3113__0;
        SData/*14:0*/ __VdfgTmp_h3f732c73__0;
        SData/*14:0*/ __VdfgTmp_hbc36f83b__0;
        SData/*14:0*/ __VdfgTmp_hfbb06ac0__0;
        SData/*14:0*/ __VdfgTmp_hfbcbb255__0;
        SData/*14:0*/ __VdfgTmp_h0609fa5a__0;
        SData/*14:0*/ __VdfgTmp_h3dfd7295__0;
        SData/*14:0*/ __VdfgTmp_h55c635c7__0;
        SData/*14:0*/ __VdfgTmp_h6b3a5eab__0;
        SData/*14:0*/ __VdfgTmp_hdaffa71e__0;
        VL_IN(io_posit_i_0,31,0);
        VL_IN(io_posit_i_1,31,0);
        VL_IN(io_posit_i_2,31,0);
        VL_IN(io_posit_i_3,31,0);
        VL_IN(io_posit_i_4,31,0);
        VL_IN(io_posit_i_5,31,0);
        VL_IN(io_posit_i_6,31,0);
        VL_IN(io_posit_i_7,31,0);
        VL_IN(io_posit_i_8,31,0);
        VL_IN(io_posit_i_9,31,0);
        VL_IN(io_posit_i_10,31,0);
        VL_IN(io_posit_i_11,31,0);
        VL_IN(io_posit_i_12,31,0);
        VL_IN(io_posit_i_13,31,0);
        VL_IN(io_posit_i_14,31,0);
        VL_IN(io_posit_i_15,31,0);
        VL_OUT(io_posit_o_0,31,0);
        VL_OUT(io_posit_o_1,31,0);
        VL_OUT(io_posit_o_2,31,0);
        VL_OUT(io_posit_o_3,31,0);
    };
    struct {
        VL_OUT(io_posit_o_4,31,0);
        VL_OUT(io_posit_o_5,31,0);
        VL_OUT(io_posit_o_6,31,0);
        VL_OUT(io_posit_o_7,31,0);
        VL_OUT(io_posit_o_8,31,0);
        VL_OUT(io_posit_o_9,31,0);
        VL_OUT(io_posit_o_10,31,0);
        VL_OUT(io_posit_o_11,31,0);
        VL_OUT(io_posit_o_12,31,0);
        VL_OUT(io_posit_o_13,31,0);
        VL_OUT(io_posit_o_14,31,0);
        VL_OUT(io_posit_o_15,31,0);
        VL_OUT(io_int_o_0,31,0);
        VL_OUT(io_int_o_1,31,0);
        VL_OUT(io_int_o_2,31,0);
        VL_OUT(io_int_o_3,31,0);
        VL_OUT(io_int_o_4,31,0);
        VL_OUT(io_int_o_5,31,0);
        VL_OUT(io_int_o_6,31,0);
        VL_OUT(io_int_o_7,31,0);
        VL_OUT(io_int_o_8,31,0);
        VL_OUT(io_int_o_9,31,0);
        VL_OUT(io_int_o_10,31,0);
        VL_OUT(io_int_o_11,31,0);
        VL_OUT(io_int_o_12,31,0);
        VL_OUT(io_int_o_13,31,0);
        VL_OUT(io_int_o_14,31,0);
        VL_OUT(io_int_o_15,31,0);
        VlWide<12>/*383:0*/ QvuTop__DOT____Vcellout__floatDecode__io_Frac;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___barrel_shifter_15_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___barrel_shifter_14_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___barrel_shifter_13_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___barrel_shifter_12_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___barrel_shifter_11_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___barrel_shifter_10_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___barrel_shifter_9_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___barrel_shifter_8_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___barrel_shifter_7_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___barrel_shifter_6_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___barrel_shifter_5_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___barrel_shifter_4_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___barrel_shifter_3_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___barrel_shifter_2_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___barrel_shifter_1_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___barrel_shifter_io_result_o;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___operand_0_T_6;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___operand_1_T_6;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___operand_2_T_6;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___operand_3_T_6;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___operand_4_T_6;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___operand_5_T_6;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___operand_6_T_6;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___operand_7_T_6;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___operand_8_T_6;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___operand_9_T_6;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___operand_10_T_6;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___operand_11_T_6;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___operand_12_T_6;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___operand_13_T_6;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___operand_14_T_6;
        IData/*30:0*/ QvuTop__DOT__decode__DOT___operand_15_T_6;
        IData/*22:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h907e46d1__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h93fcca7b__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8fff338c__0;
    };
    struct {
        IData/*22:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8f719326__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8effb80f__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8e62d0a5__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8de56522__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8d7f6188__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8cea4ac5__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8c68d66f__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8beafdc8__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8b7d4662__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8a383c23__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h898ddcf9__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h8933512e__0;
        IData/*22:0*/ QvuTop__DOT__floatDecode__DOT____VdfgTmp_h88bc2594__0;
        IData/*19:0*/ QvuTop__DOT__quantizeInt4__DOT__histogramTotal;
        IData/*31:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftedFrac;
        IData/*31:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftedFrac_1;
        IData/*31:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftedFrac_2;
        IData/*31:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftedFrac_3;
        IData/*31:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftedFrac_4;
        IData/*31:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftedFrac_5;
        IData/*31:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftedFrac_6;
        IData/*31:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftedFrac_7;
        IData/*31:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftedFrac_8;
        IData/*31:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftedFrac_9;
        IData/*31:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftedFrac_10;
        IData/*31:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftedFrac_11;
        IData/*31:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftedFrac_12;
        IData/*31:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftedFrac_13;
        IData/*31:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftedFrac_14;
        IData/*31:0*/ QvuTop__DOT__quantizeInt4__DOT__shiftedFrac_15;
        IData/*19:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___cdf_1_T;
        IData/*19:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___cdf_2_T;
        IData/*19:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___cdf_3_T;
        IData/*19:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___cdf_4_T;
        IData/*19:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___cdf_5_T;
        IData/*19:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___cdf_6_T;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_70;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__lowerThreshold;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___upperThreshold_T;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_71;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_72;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_73;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_74;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_75;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_76;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_77;
        IData/*22:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___GEN_78;
        IData/*27:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hdf96a6fc__0;
        IData/*27:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hdcaf2b43__0;
        IData/*27:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hd95c8805__0;
        IData/*27:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hd9d61bde__0;
        IData/*27:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hde5471e5__0;
        IData/*27:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hded989a1__0;
        IData/*27:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hc34698b0__0;
        IData/*27:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hc3a14e76__0;
        IData/*27:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hc036deeb__0;
        IData/*27:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hc0a02867__0;
        IData/*27:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hdd210c4c__0;
        IData/*27:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hddc85dc2__0;
        IData/*27:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hc24eba09__0;
        IData/*27:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hc2bd0e7e__0;
        IData/*27:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_he76a7da4__0;
        IData/*27:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_he7d4d037__0;
        IData/*24:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hdc3001b5__0;
    };
    struct {
        IData/*24:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hdc8dcd07__0;
        IData/*24:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hd93d690c__0;
        IData/*24:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hd9b73fc0__0;
        IData/*24:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hde2b96ae__0;
        IData/*24:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hdeb92de4__0;
        IData/*24:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hc326fab3__0;
        IData/*24:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hc380ef73__0;
        IData/*24:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hc017bafb__0;
        IData/*24:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hc08300e3__0;
        IData/*24:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hdd270b9c__0;
        IData/*24:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hddabf1ae__0;
        IData/*24:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hc2281910__0;
        IData/*24:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_hc29e61ec__0;
        IData/*24:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_he78bd7e7__0;
        IData/*24:0*/ QvuTop__DOT__quantizeFP4__DOT____VdfgTmp_he40a7e5d__0;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_15____PVT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_14____PVT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_13____PVT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_12____PVT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_11____PVT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_10____PVT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_9____PVT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_8____PVT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_7____PVT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_6____PVT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_5____PVT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_4____PVT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_3____PVT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_2____PVT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule_1____PVT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __Vtrigrprev__TOP__QvuTop__DOT__decode__DOT__lzcModule____PVT__gen_lzc__DOT__sel_nodes;
        IData/*31:0*/ __VstlIterCount;
        IData/*31:0*/ __VicoIterCount;
        IData/*31:0*/ __VactIterCount;
        VL_IN64(io_float_i_0,63,0);
        VL_IN64(io_float_i_1,63,0);
        VL_IN64(io_float_i_2,63,0);
        VL_IN64(io_float_i_3,63,0);
        VL_IN64(io_float_i_4,63,0);
        VL_IN64(io_float_i_5,63,0);
        VL_IN64(io_float_i_6,63,0);
        VL_IN64(io_float_i_7,63,0);
        VL_IN64(io_float_i_8,63,0);
        VL_IN64(io_float_i_9,63,0);
        VL_IN64(io_float_i_10,63,0);
        VL_IN64(io_float_i_11,63,0);
        VL_IN64(io_float_i_12,63,0);
        VL_IN64(io_float_i_13,63,0);
        VL_IN64(io_float_i_14,63,0);
        VL_IN64(io_float_i_15,63,0);
        VL_OUT64(io_float_o_0,63,0);
        VL_OUT64(io_float_o_1,63,0);
        VL_OUT64(io_float_o_2,63,0);
        VL_OUT64(io_float_o_3,63,0);
        VL_OUT64(io_float_o_4,63,0);
        VL_OUT64(io_float_o_5,63,0);
        VL_OUT64(io_float_o_6,63,0);
        VL_OUT64(io_float_o_7,63,0);
        VL_OUT64(io_float_o_8,63,0);
        VL_OUT64(io_float_o_9,63,0);
        VL_OUT64(io_float_o_10,63,0);
        VL_OUT64(io_float_o_11,63,0);
        VL_OUT64(io_float_o_12,63,0);
        VL_OUT64(io_float_o_13,63,0);
    };
    struct {
        VL_OUT64(io_float_o_14,63,0);
        VL_OUT64(io_float_o_15,63,0);
        VlWide<17>/*527:0*/ QvuTop__DOT____Vcellinp__quantizeInt8__io_pir_frac_i;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__globalMax;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__globalMin;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__globalScale;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__globalOffset;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__batchMax;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__batchMin;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_1;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_4;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_7;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_10;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_13;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_16;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_19;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_22;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_25;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_28;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_31;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_34;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_37;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_40;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_43;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_46;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_48;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__scaledValue;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__remainder;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__tempIdx;
        QData/*36:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_50;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT___GEN_51;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__quantizedValue;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__scaledValue_1;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__remainder_1;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__tempIdx_1;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__quantizedValue_1;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__scaledValue_2;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__remainder_2;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__tempIdx_2;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__quantizedValue_2;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__scaledValue_3;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__remainder_3;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__tempIdx_3;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__quantizedValue_3;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__scaledValue_4;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__remainder_4;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__tempIdx_4;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__quantizedValue_4;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__scaledValue_5;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__remainder_5;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__tempIdx_5;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__quantizedValue_5;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__scaledValue_6;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__remainder_6;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__tempIdx_6;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__quantizedValue_6;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__scaledValue_7;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__remainder_7;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__tempIdx_7;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__quantizedValue_7;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__scaledValue_8;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__remainder_8;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__tempIdx_8;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__quantizedValue_8;
    };
    struct {
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__scaledValue_9;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__remainder_9;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__tempIdx_9;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__quantizedValue_9;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__scaledValue_10;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__remainder_10;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__tempIdx_10;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__quantizedValue_10;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__scaledValue_11;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__remainder_11;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__tempIdx_11;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__quantizedValue_11;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__scaledValue_12;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__remainder_12;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__tempIdx_12;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__quantizedValue_12;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__scaledValue_13;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__remainder_13;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__tempIdx_13;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__quantizedValue_13;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__scaledValue_14;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__remainder_14;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__tempIdx_14;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__quantizedValue_14;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__scaledValue_15;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__remainder_15;
        QData/*33:0*/ QvuTop__DOT__quantizeInt4__DOT__tempIdx_15;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__quantizedValue_15;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT___dataRange_T;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__binWidth_16;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__effectiveMin;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__effectiveMax;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk2__DOT___dataRange_T_8;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk2__DOT___dataRange_T_15;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk2__DOT___mid_T;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___binWidth_T;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__binWidth;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___tempIndex_T;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__tempIndex;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___binWidth_T_11;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__binWidth_1;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___tempIndex_T_9;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__tempIndex_1;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___binWidth_T_22;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__binWidth_2;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___tempIndex_T_18;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__tempIndex_2;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___binWidth_T_33;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__binWidth_3;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___tempIndex_T_27;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__tempIndex_3;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___binWidth_T_44;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__binWidth_4;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___tempIndex_T_36;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__tempIndex_4;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___binWidth_T_55;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__binWidth_5;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___tempIndex_T_45;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__tempIndex_5;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___binWidth_T_66;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__binWidth_6;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___tempIndex_T_54;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__tempIndex_6;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___binWidth_T_77;
    };
    struct {
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__binWidth_7;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___tempIndex_T_63;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__tempIndex_7;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___binWidth_T_88;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__binWidth_8;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___tempIndex_T_72;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__tempIndex_8;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___binWidth_T_99;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__binWidth_9;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___tempIndex_T_81;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__tempIndex_9;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___binWidth_T_110;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__binWidth_10;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___tempIndex_T_90;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__tempIndex_10;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___binWidth_T_121;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__binWidth_11;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___tempIndex_T_99;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__tempIndex_11;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___binWidth_T_132;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__binWidth_12;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___tempIndex_T_108;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__tempIndex_12;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___binWidth_T_143;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__binWidth_13;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___tempIndex_T_117;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__tempIndex_13;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___binWidth_T_154;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__binWidth_14;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___tempIndex_T_126;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__tempIndex_14;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___binWidth_T_165;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__binWidth_15;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT___tempIndex_T_135;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT__unnamedblk1__DOT__unnamedblk3__DOT__tempIndex_15;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_h0de0d3f7__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hcbc32e41__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_h39952376__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hca8bba58__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_h50e13622__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_h1ac14696__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_h4af495e2__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hc40f109e__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_h44842b86__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hae55fc57__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_h159e3222__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_h2c756526__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_he7b16fba__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_h601d99d2__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hff625ee6__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_h9762a8ae__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hdf96a634__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hdcaf4442__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hd95c8ec3__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hd9d61d93__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hde54723b__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hded98ee5__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hc3469bf4__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hc3a14928__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hc036df2f__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hc0a02ab9__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hdd210b92__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hddc85c86__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hc24eb5f8__0;
    };
    struct {
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_hc2bd0cb6__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_he76a7ee9__0;
        QData/*32:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_he7d4d071__0;
        QData/*36:0*/ QvuTop__DOT__quantizeInt4__DOT____VdfgTmp_h5d60b427__0;
        VlWide<9>/*263:0*/ QvuTop__DOT__quantizeFP4__DOT__windowMax;
        VlWide<9>/*263:0*/ QvuTop__DOT__quantizeFP4__DOT__windowMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__globalMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__globalMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__globalScale;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__batchMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__batchMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT___GEN;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT___GEN_0;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT___GEN_1;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT___GEN_2;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT___GEN_3;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT___GEN_4;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT___GEN_5;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT___GEN_6;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT___GEN_7;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT___GEN_8;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT___GEN_9;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT___GEN_10;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT___GEN_11;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT___GEN_12;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT___GEN_13;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT___GEN_14;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__valueAbs;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__valueAbs_1;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__valueAbs_2;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__valueAbs_3;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__valueAbs_4;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__valueAbs_5;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__valueAbs_6;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__valueAbs_7;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__valueAbs_8;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__valueAbs_9;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__valueAbs_10;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__valueAbs_11;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__valueAbs_12;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__valueAbs_13;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__valueAbs_14;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__valueAbs_15;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_leftMax_leftMax_leftMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_leftMax_leftMax_rightMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_leftMax_leftMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_leftMax_rightMax_leftMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_leftMax_rightMax_rightMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_leftMax_rightMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_leftMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_rightMax_leftMax_leftMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_rightMax_leftMax_rightMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_rightMax_leftMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_rightMax_rightMax_leftMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_rightMax_rightMax_rightMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_rightMax_rightMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax_rightMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMax;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_leftMin_leftMin_leftMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_leftMin_leftMin_rightMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_leftMin_leftMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_leftMin_rightMin_leftMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_leftMin_rightMin_rightMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_leftMin_rightMin;
    };
    struct {
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_leftMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_rightMin_leftMin_leftMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_rightMin_leftMin_rightMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_rightMin_leftMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_rightMin_rightMin_leftMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_rightMin_rightMin_rightMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_rightMin_rightMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin_rightMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__effectiveMin;
        QData/*32:0*/ QvuTop__DOT__quantizeFP4__DOT__unnamedblk2__DOT__unnamedblk3__DOT__dataRange;
        QData/*32:0*/ __VdfgTmp_h93c7e7df__0;
        QData/*32:0*/ __VdfgTmp_h3180c58e__0;
        QData/*32:0*/ __VdfgTmp_hc3fa4165__0;
        QData/*32:0*/ __VdfgTmp_h3aa8e614__0;
        QData/*32:0*/ __VdfgTmp_hdbad544b__0;
        QData/*32:0*/ __VdfgTmp_h33db8eb5__0;
        QData/*32:0*/ __VdfgTmp_h2a607f05__0;
        QData/*32:0*/ __VdfgTmp_h63efa7e5__0;
        QData/*32:0*/ __VdfgTmp_h447ba768__0;
        QData/*32:0*/ __VdfgTmp_hc1d7047f__0;
        QData/*32:0*/ __VdfgTmp_h5acc59ba__0;
        QData/*32:0*/ __VdfgTmp_he5a8b1b2__0;
        QData/*32:0*/ __VdfgTmp_h28105e05__0;
        QData/*32:0*/ __VdfgTmp_h82595622__0;
        QData/*32:0*/ __VdfgTmp_hf483a44e__0;
        QData/*32:0*/ __VdfgTmp_h5939b817__0;
        VlUnpacked<CData/*0:0*/, 39> __Vm_traceActivity;
    };
    VlTriggerVec<33> __VstlTriggered;
    VlTriggerVec<33> __VicoTriggered;
    VlTriggerVec<33> __VactTriggered;
    VlTriggerVec<33> __VnbaTriggered;

    // INTERNAL VARIABLES
    VQvuTop__Syms* const vlSymsp;

    // CONSTRUCTORS
    VQvuTop___024root(VQvuTop__Syms* symsp, const char* v__name);
    ~VQvuTop___024root();
    VL_UNCOPYABLE(VQvuTop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
